name: Test hello package
on: push
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ It's works"
      - run: echo "ğŸ™ ${{github.repository}}"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.12' 
      - run: go version